trigger:
- master

schedules:
- cron: "0 16 * * Mon-Fri" # 5pm every week day
  displayName: "Daily update" # friendly name given to a specific schedule
  branches:
    include:
      - master 

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: Update MI information
  inputs:
    azureSubscription: 'azurerm-prod'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'update-all.sh'
