trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: Update MI information
  inputs:
    azureSubscription: 'azurerm-prod'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'update-all.sh'
