trigger:
- master

schedules:
- cron: "0 16 * * Mon-Fri" # 5pm every week day
  displayName: "Daily update" # friendly name given to a specific schedule
  branches:
    include:
      - master
  always: 'true'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -LO https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
      sudo dpkg -i ripgrep_11.0.2_amd64.deb
- task: AzureCLI@2
  displayName: Update MI information
  inputs:
    azureSubscription: 'azurerm-prod'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'update-all.sh'
